# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "FILE" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"state" INTEGER NOT NULL,"dir" BOOLEAN NOT NULL,"parent" VARCHAR NOT NULL,"position" BIGINT NOT NULL);

# --- !Downs

drop table "FILE";

